/*
 * marble-yellow-spectrum — palette-aware xwww scene (generated by build_scenes.py).
 *
 * Layers:
 *   shape.jpg   Rec.709 luminance of the artwork, remapped through the active
 *               palette ramp, so the whole picture restyles with the theme.
 *   accent.png  chroma stencil of the secondary hues, tinted with a palette accent
 *
 * The scene repaints only when the palette changes, so it costs no CPU while
 * idle (the xwww engine sends a frame only when the canvas changed).
 *
 *   xwww scene render scene.js -o out.png --size 2560x1440 --palette equisdots
 *   xwww scene run    scene.js --fps 2 --timeout-ms 2000 --palette equisdots
 */

const HAS_ACCENT = true;

/* base16 slot that matches the original artwork's dominant hue (-1 = neutral).
   Each wallpaper leans on a different part of the palette, so the marble
   variants keep their distinct character instead of all collapsing to grey. */
const ANCHOR = 3;

function channels(hex) {
  const s = hex.replace(/^#/, "");
  return [
    parseInt(s.slice(0, 2), 16) || 0,
    parseInt(s.slice(2, 4), 16) || 0,
    parseInt(s.slice(4, 6), 16) || 0,
  ];
}

function luma(hex) {
  const [r, g, b] = channels(hex);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/* Build the recolor ramp from the palette. The artwork shadows take the
   darkest palette color, the body takes the anchor slot (its original hue) and
   the highlights take the brightest one; sorting by luminance keeps the result
   readable on both dark and light themes. */
function paletteRamp(p) {
  const mid = ANCHOR >= 0 && p.colors.length > ANCHOR ? p.colors[ANCHOR].hex : p.colors[8].hex;
  const bright = ANCHOR >= 0 && p.colors.length > ANCHOR + 8 ? p.colors[ANCHOR + 8].hex : null;
  const stops = [p.background.hex, mid, bright, p.foreground.hex];
  const uniq = [];
  for (let i = 0; i < stops.length; i++) {
    if (stops[i] && uniq.indexOf(stops[i]) < 0) uniq.push(stops[i]);
  }
  uniq.sort(function (a, b) { return luma(a) - luma(b); });
  return uniq;
}

function secondary(p) {
  if (p.roles && p.roles.workspaceActive) return p.roles.workspaceActive.hex;
  if (p.colors.length > 13) return p.colors[13].hex;
  if (p.colors.length > 5) return p.colors[5].hex;
  return p.foreground.hex;
}

let signature = null;

function render(t, ctx) {
  const p = ctx.palette;
  const next = [p.slug, p.background.hex, p.foreground.hex]
    .concat(p.colors.map(function (c) { return c.hex; }))
    .join("|");
  if (next === signature) {
    return;
  }
  signature = next;

  canvas.clear(p.background.hex);
  canvas.image("shape.jpg", 0, 0, ctx.width, ctx.height);
  canvas.remap(0, 0, ctx.width, ctx.height, paletteRamp(p), 1.0);

  if (HAS_ACCENT) {
    canvas.alpha(0.55);
    canvas.image_tinted("accent.png", 0, 0, ctx.width, ctx.height, secondary(p));
    canvas.alpha(1.0);
  }
}
