/*
 * marble-yellow-black — palette-aware xwww scene (generated by build_scenes.py).
 *
 * Layers:
 *   shape.jpg   Rec.709 luminance of the artwork, remapped through the palette
 *               ramp: the artwork background takes the palette `background`
 *               (so it turns white on light themes, like the astro scenes) and
 *               the ink takes the palette accent/foreground.
 *   accent.png  not generated (the artwork has a single dominant hue)
 *
 * The scene repaints only when the palette changes, so it costs no CPU while
 * idle (the xwww engine sends a frame only when the canvas changed).
 *
 *   xwww scene render scene.js -o out.png --size 2560x1440 --palette equisdots
 *   xwww scene run    scene.js --fps 2 --timeout-ms 2000 --palette equisdots
 */

const HAS_ACCENT = false;

/* base16 slot that matches the original artwork's dominant hue (-1 = neutral).
   Each wallpaper leans on a different part of the palette, so the marble
   variants keep their distinct character instead of all collapsing to grey. */
const ANCHOR = 3;

/* Source artwork size, used to letterbox-free "cover" fit at any output. */
const IMG_W = 2560;
const IMG_H = 1440;

/* True when the artwork background is light (paper, bright marble). The engine
   sorts the ramp by luminance, so to keep the artwork background on the palette
   background we pick the normal or the inverted luminance layer per palette. */
const ART_LIGHT = false;

function channels(hex) {
  const s = hex.replace(/^#/, "");
  return [
    parseInt(s.slice(0, 2), 16) || 0,
    parseInt(s.slice(2, 4), 16) || 0,
    parseInt(s.slice(4, 6), 16) || 0,
  ];
}

function luma(hex) {
  const [r, g, b] = channels(hex);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

/* Ramp stops for canvas.remap. The engine sorts them by luminance, so the
   order here does not matter; the anchor keeps each wallpaper's own hue. */
function paletteRamp(p) {
  const mid = ANCHOR >= 0 && p.colors.length > ANCHOR ? p.colors[ANCHOR].hex : p.colors[8].hex;
  const bright = ANCHOR >= 0 && p.colors.length > ANCHOR + 8 ? p.colors[ANCHOR + 8].hex : null;
  const stops = [];
  [p.background.hex, mid, bright, p.foreground.hex].forEach(function (c) {
    if (c && stops.indexOf(c) < 0) stops.push(c);
  });
  return stops;
}

function secondary(p) {
  if (p.roles && p.roles.workspaceActive) return p.roles.workspaceActive.hex;
  if (p.colors.length > 13) return p.colors[13].hex;
  if (p.colors.length > 5) return p.colors[5].hex;
  return p.foreground.hex;
}

/* Cover fit: scale the artwork to fill the canvas and crop the overflow, so a
   4:3 or portrait wallpaper is never stretched on a 16:9 display. */
function coverBox(ctx) {
  const out = ctx.width / ctx.height;
  const src = IMG_W / IMG_H;
  if (out > src) {
    const w = ctx.width;
    const h = Math.round(w / src);
    return [0, Math.round((ctx.height - h) / 2), w, h];
  }
  const h = ctx.height;
  const w = Math.round(h * src);
  return [Math.round((ctx.width - w) / 2), 0, w, h];
}

let signature = null;

function render(t, ctx) {
  const p = ctx.palette;
  const next = [p.slug, p.background.hex, p.foreground.hex]
    .concat(p.colors.map(function (c) { return c.hex; }))
    .join("|");
  if (next === signature) {
    return;
  }
  signature = next;

  const box = coverBox(ctx);
  /* Keep the artwork background on the palette background whatever the theme:
     a light palette needs the inverted luminance layer and vice versa. */
  const bgLight = luma(p.background.hex) > luma(p.foreground.hex);
  const layer = bgLight === ART_LIGHT ? "shape.jpg" : "shape_inv.jpg";

  canvas.clear(p.background.hex);
  canvas.image(layer, box[0], box[1], box[2], box[3]);
  canvas.remap(box[0], box[1], box[2], box[3], paletteRamp(p), 1.0);

  if (HAS_ACCENT) {
    canvas.alpha(0.55);
    canvas.image_tinted("accent.png", box[0], box[1], box[2], box[3], secondary(p));
    canvas.alpha(1.0);
  }
}
